### ISSUE TITLE
[Bug] Threads are no indented properly, causing overlapping issues

### ISSUE THREAD

**Issue by Crec0** [RockESV/Eris#3]
## Issue

Threads are styled with `.typeThread-2Aqh6X .content-1gYQeQ` however, only `.content-1gYQeQ` is used to style the channels at https://github.com/RockESV/Eris/blob/main/ErisSource.css#L123-L128

This is causes overlapping issues with the `L` shape svg spline. Since the svg is done before the thread list and is therefore outside the scope of `.content-1gYQeQ` unlike channels where it's within it's scope.

![image](https://user-images.githubusercontent.com/83436716/173252815-765dd433-7688-42c5-9125-d33eea47ba6a.png)

### Workaround for this indentation issue:

Add this css snippet to overwrite margin applied by `.content-1gYQeQ` and z-index the spline so it doesn't overlap with selection.
```css
.typeThread-2Aqh6X {
    text-indent: 1.625rem !important;
}

.spine-29OFwR {
    z-index: 1 !important;
}
```
Using the above fix, the result looks like this:
![image](https://user-images.githubusercontent.com/83436716/173253111-32cddab0-ebb5-465c-8ed7-f85c55d26c5d.png)
